import { MotionTemplateManifest } from '../types/editor'

export const motionTemplates: MotionTemplateManifest[] = [
  {
    id: 'hero_title',
    version: 1,
    name: 'Hero title',
    category: 'Titles',
    engine: 'remotion',
    defaultDurationSec: 4,
    supportsTransparency: false,
    fields: [
      { id: 'title', label: 'Title', type: 'text', defaultValue: 'A story worth seeing' },
      { id: 'body', label: 'Supporting text', type: 'text', defaultValue: 'Built from your narration' },
      { id: 'accent', label: 'Accent', type: 'color', defaultValue: '#8b5cf6' },
    ],
  },
  {
    id: 'statistic',
    version: 1,
    name: 'Statistic reveal',
    category: 'Data',
    engine: 'remotion',
    defaultDurationSec: 4,
    supportsTransparency: false,
    fields: [
      { id: 'title', label: 'Statistic', type: 'text', defaultValue: '72%' },
      { id: 'body', label: 'Label', type: 'text', defaultValue: 'More memorable with motion' },
      { id: 'accent', label: 'Accent', type: 'color', defaultValue: '#22d3ee' },
    ],
  },
  {
    id: 'quote',
    version: 1,
    name: 'Quote card',
    category: 'Editorial',
    engine: 'remotion',
    defaultDurationSec: 5,
    supportsTransparency: false,
    fields: [
      { id: 'title', label: 'Quote', type: 'text', defaultValue: 'Editing should clarify the idea, not hide it.' },
      { id: 'body', label: 'Attribution', type: 'text', defaultValue: 'Rhymx Studio' },
      { id: 'accent', label: 'Accent', type: 'color', defaultValue: '#f59e0b' },
    ],
  },
  {
    id: 'progress_bar',
    version: 1,
    name: 'Progress bar',
    category: 'Data',
    engine: 'remotion',
    defaultDurationSec: 4,
    supportsTransparency: false,
    fields: [
      { id: 'title', label: 'Label', type: 'text', defaultValue: 'Project complete' },
      { id: 'value', label: 'Percent', type: 'number', defaultValue: 72 },
      { id: 'accent', label: 'Accent', type: 'color', defaultValue: '#34d399' },
    ],
  },
  {
    id: 'lower_third',
    version: 1,
    name: 'Lower third',
    category: 'Titles',
    engine: 'remotion',
    defaultDurationSec: 4,
    supportsTransparency: false,
    fields: [
      { id: 'title', label: 'Name', type: 'text', defaultValue: 'Alex Morgan' },
      { id: 'body', label: 'Role', type: 'text', defaultValue: 'Creative director' },
      { id: 'accent', label: 'Accent', type: 'color', defaultValue: '#2dd4bf' },
    ],
  },
  {
    id: 'split_comparison',
    version: 1,
    name: 'Split comparison',
    category: 'Data',
    engine: 'remotion',
    defaultDurationSec: 5,
    supportsTransparency: false,
    fields: [
      { id: 'title', label: 'Heading', type: 'text', defaultValue: 'Before and after' },
      { id: 'left', label: 'Left side', type: 'text', defaultValue: 'Manual workflow' },
      { id: 'right', label: 'Right side', type: 'text', defaultValue: 'Creative flow' },
      { id: 'accent', label: 'Accent', type: 'color', defaultValue: '#38bdf8' },
    ],
  },
  {
    id: 'checklist',
    version: 1,
    name: 'Animated checklist',
    category: 'Lists',
    engine: 'remotion',
    defaultDurationSec: 5,
    supportsTransparency: false,
    fields: [
      { id: 'title', label: 'Heading', type: 'text', defaultValue: 'Ready to publish' },
      { id: 'item1', label: 'Item 1', type: 'text', defaultValue: 'A clear story' },
      { id: 'item2', label: 'Item 2', type: 'text', defaultValue: 'Strong visuals' },
      { id: 'item3', label: 'Item 3', type: 'text', defaultValue: 'Clean captions' },
      { id: 'accent', label: 'Accent', type: 'color', defaultValue: '#4ade80' },
    ],
  },
  {
    id: 'countdown',
    version: 1,
    name: 'Countdown',
    category: 'Transitions',
    engine: 'remotion',
    defaultDurationSec: 5,
    supportsTransparency: false,
    fields: [
      { id: 'title', label: 'Heading', type: 'text', defaultValue: 'Launching in' },
      { id: 'value', label: 'Starting number', type: 'number', defaultValue: 5 },
      { id: 'body', label: 'Footer', type: 'text', defaultValue: 'Get ready' },
      { id: 'accent', label: 'Accent', type: 'color', defaultValue: '#fb7185' },
    ],
  },
  {
    id: 'chapter_card',
    version: 1,
    name: 'Chapter card',
    category: 'Titles',
    engine: 'remotion',
    defaultDurationSec: 4,
    supportsTransparency: false,
    fields: [
      { id: 'label', label: 'Chapter', type: 'text', defaultValue: 'Chapter 03' },
      { id: 'title', label: 'Title', type: 'text', defaultValue: 'Finding the signal' },
      { id: 'body', label: 'Subtitle', type: 'text', defaultValue: 'What the data is really saying' },
      { id: 'accent', label: 'Accent', type: 'color', defaultValue: '#c084fc' },
    ],
  },
  {
    id: 'social_callout',
    version: 1,
    name: 'Social callout',
    category: 'Calls to action',
    engine: 'remotion',
    defaultDurationSec: 4,
    supportsTransparency: false,
    fields: [
      { id: 'label', label: 'Handle', type: 'text', defaultValue: '@rhymxstudio' },
      { id: 'title', label: 'Message', type: 'text', defaultValue: 'Follow the next idea' },
      { id: 'body', label: 'Call to action', type: 'text', defaultValue: 'Save - share - remix' },
      { id: 'accent', label: 'Accent', type: 'color', defaultValue: '#f472b6' },
    ],
  },
  {
    id: 'feature_grid',
    version: 1,
    name: 'Feature grid',
    category: 'Lists',
    engine: 'remotion',
    defaultDurationSec: 5,
    supportsTransparency: false,
    fields: [
      { id: 'title', label: 'Heading', type: 'text', defaultValue: 'Everything in one flow' },
      { id: 'item1', label: 'Feature 1', type: 'text', defaultValue: 'Smart scenes' },
      { id: 'item2', label: 'Feature 2', type: 'text', defaultValue: 'Fast edits' },
      { id: 'item3', label: 'Feature 3', type: 'text', defaultValue: 'Clean export' },
      { id: 'accent', label: 'Accent', type: 'color', defaultValue: '#fbbf24' },
    ],
  },
  {
    id: 'kinetic_title',
    version: 1,
    name: 'Kinetic title',
    category: 'Advanced motion',
    engine: 'hyperframes',
    defaultDurationSec: 5,
    supportsTransparency: false,
    fields: [
      { id: 'title', label: 'Title', type: 'text', defaultValue: 'Momentum changes everything' },
      { id: 'body', label: 'Supporting text', type: 'text', defaultValue: 'Kinetic typography' },
      { id: 'accent', label: 'Accent', type: 'color', defaultValue: '#ec4899' },
    ],
  },
  {
    id: 'product_card',
    version: 1,
    name: 'Product launch',
    category: 'Advanced motion',
    engine: 'hyperframes',
    defaultDurationSec: 6,
    supportsTransparency: false,
    fields: [
      { id: 'title', label: 'Product', type: 'text', defaultValue: 'Meet the next chapter' },
      { id: 'body', label: 'Tagline', type: 'text', defaultValue: 'Designed to move with the story' },
      { id: 'accent', label: 'Accent', type: 'color', defaultValue: '#a78bfa' },
    ],
  },
  {
    id: 'end_card',
    version: 1,
    name: 'End card',
    category: 'Calls to action',
    engine: 'hyperframes',
    defaultDurationSec: 5,
    supportsTransparency: false,
    fields: [
      { id: 'title', label: 'Message', type: 'text', defaultValue: 'Keep the story moving' },
      { id: 'body', label: 'Call to action', type: 'text', defaultValue: 'rhymx.app' },
      { id: 'accent', label: 'Accent', type: 'color', defaultValue: '#60a5fa' },
    ],
  },
]
