import React, { useState } from 'react'
import {
  ArrowRight,
  AudioLines,
  Captions,
  Check,
  ChevronDown,
  Database,
  Film,
  Gauge,
  Images,
  Layers3,
  Menu,
  MousePointer2,
  Play,
  Search,
  ShieldCheck,
  Sparkles,
  WandSparkles,
  X,
} from 'lucide-react'
import { RouteLink, navigate } from './routing'

const features = [
  { icon: AudioLines, title: 'Narration to timeline', copy: 'Groq transcription keeps word timing, detects scenes, and turns spoken ideas into visual search phrases.' },
  { icon: Images, title: 'Free media library', copy: 'Search Pexels, Pixabay, Archive.org, NASA, and Wikimedia through one consistent media browser.' },
  { icon: WandSparkles, title: 'Smart montage', copy: 'Ranked matches from multiple providers, with scene-by-scene approval before anything downloads.' },
  { icon: Sparkles, title: 'Motion graphics', copy: 'Choose integrated Remotion scenes or advanced, template-driven motion for high-impact moments.' },
  { icon: Layers3, title: 'Editable, not one-shot', copy: 'Keep the timeline, multiple tracks, captions, media replacement, transforms, and undo/redo.' },
  { icon: Gauge, title: 'Local-first export', copy: 'Preview and export with the same composition, using browser-native WebCodecs rendering.' },
  { icon: ShieldCheck, title: 'Responsible sourcing', copy: 'Provider, creator, license, warnings, and attribution remain attached to every used asset.' },
]

const faqs = [
  ['Is Rhymx free?', 'Guest editing is free during this preview. Media providers can enforce their own quotas, and future hosted features may have separate limits.'],
  ['Do I need API keys?', 'Groq, Pexels, and YouTube features use keys you add in Settings. Keys stay outside project files and are sent directly to the provider you invoke; Wikimedia remains keyless.'],
  ['Is my media uploaded?', 'Imported files and projects stay in browser storage. Narration is sent to Groq only when you request transcription. Selected remote media is acquired into local project storage.'],
  ['Can I edit generated scenes?', 'Yes. Every scene, caption, timing, track, media choice, transform, and motion-template value remains editable.'],
  ['Where does stock footage come from?', 'Rhymx searches Pexels, Pixabay, Archive.org, NASA, and Wikimedia Commons and preserves the original landing page.'],
  ['Can I use the output commercially?', 'Possibly, but not automatically. Rights vary by asset. Rhymx surfaces license and attribution details; you must review warnings and verify rights for your use.'],
  ['Which browsers are supported?', 'Current Chromium-based browsers provide the best experience for local storage and WebCodecs export. Other modern browsers can use the editor with reduced export compatibility.'],
  ['Are accounts required?', 'No. The editor works in guest mode, and accounts are intentionally not enabled yet.'],
]

function Brand() {
  return <RouteLink href="/" className="inline-flex items-center gap-2.5 font-semibold tracking-tight"><span className="h-9 w-9 rounded-xl bg-violet-600 text-white flex items-center justify-center shadow-lg shadow-violet-950/60"><Film className="h-4.5 w-4.5" /></span><span>Rhymx</span></RouteLink>
}

function DemoTimeline() {
  const [active, setActive] = useState(1)
  const scenes = [
    { time: '00:00', title: 'A quieter beginning', color: 'from-indigo-700 to-violet-950' },
    { time: '00:05', title: 'Cities start to move', color: 'from-cyan-700 to-slate-950' },
    { time: '00:11', title: 'The number that matters', color: 'from-fuchsia-700 to-violet-950' },
    { time: '00:17', title: 'Where we go next', color: 'from-amber-600 to-slate-950' },
  ]
  return (
    <div className="landing-demo rounded-[28px] border border-white/10 bg-[#0b0d12] shadow-2xl shadow-black/50 overflow-hidden" aria-label="Interactive Rhymx timeline demonstration">
      <div className="h-12 border-b border-white/8 flex items-center justify-between px-4"><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full bg-red-400/70" /><span className="h-2.5 w-2.5 rounded-full bg-amber-300/70" /><span className="h-2.5 w-2.5 rounded-full bg-emerald-400/70" /></div><div className="text-[10px] text-slate-500">Documentary cut · Autosaved</div><div className="rounded-md bg-violet-600 px-2.5 py-1 text-[9px]">Export</div></div>
      <div className="grid md:grid-cols-[160px_1fr] min-h-[390px]">
        <aside className="hidden md:block border-r border-white/8 p-3 bg-white/[.015]"><div className="text-[9px] uppercase tracking-[.18em] text-slate-600 mb-3">Media bin</div>{['archival-street.mp4', 'city-lights.mp4', '72-percent.motion', 'future-grid.jpg'].map((item, index) => <button key={item} onClick={() => setActive(index)} className={`w-full rounded-lg border p-2 mb-2 text-left ${active === index ? 'border-violet-400/40 bg-violet-500/10' : 'border-white/5 bg-black/20'}`}><div className={`h-12 rounded bg-gradient-to-br ${scenes[index].color}`} /><div className="text-[8px] text-slate-500 mt-1.5 truncate">{item}</div></button>)}</aside>
        <div className="flex flex-col min-w-0"><div className={`flex-1 min-h-[240px] bg-gradient-to-br ${scenes[active].color} relative overflow-hidden flex items-center justify-center p-8`}><div className="absolute inset-0 landing-grid opacity-20" /><div className="relative text-center"><div className="text-[9px] uppercase tracking-[.3em] text-white/55">Scene {active + 1}</div><div className="mt-3 text-2xl sm:text-4xl font-semibold tracking-tight text-white">{scenes[active].title}</div><div className="mt-5 inline-flex items-center gap-2 rounded-full border border-white/15 bg-black/20 px-3 py-1.5 text-[9px] text-white/70"><Play className="h-3 w-3 fill-current" />Preview composition</div></div></div><div className="h-[150px] border-t border-white/8 bg-[#101218] p-3"><div className="flex items-center gap-2 text-[8px] text-slate-600 mb-2"><span>VIDEO</span><div className="h-px bg-white/5 flex-1" /></div><div className="grid grid-cols-4 gap-1.5">{scenes.map((scene, index) => <button key={scene.time} onClick={() => setActive(index)} className={`relative rounded-md border p-1.5 text-left transition-colors ${active === index ? 'border-violet-400 bg-violet-500/10' : 'border-white/5 bg-white/[.02]'}`}><div className={`h-7 rounded bg-gradient-to-r ${scene.color}`} /><div className="text-[7px] text-slate-500 mt-1">{scene.time}</div>{active === index && <div className="absolute -top-2 left-1/2 w-px h-[83px] bg-violet-400" />}</button>)}</div><div className="flex items-center gap-2 text-[8px] text-slate-600 mt-3"><span>CAPTIONS</span><div className="h-5 flex-1 rounded bg-violet-500/10 border border-violet-400/10 px-2 flex items-center text-[7px] text-violet-200/60">Every word stays timed and editable</div></div></div></div>
      </div>
    </div>
  )
}

export default function LandingPage() {
  const [menuOpen, setMenuOpen] = useState(false)
  return (
    <div className="public-shell min-h-screen bg-[#090a0e] text-white selection:bg-violet-500/30">
      <header className="fixed top-0 inset-x-0 z-50 border-b border-white/8 bg-[#090a0e]/85 backdrop-blur-xl"><div className="max-w-7xl mx-auto h-18 px-5 sm:px-8 flex items-center justify-between"><Brand /><nav className="hidden lg:flex items-center gap-7 text-xs text-slate-400"><a href="#features" className="hover:text-white">Features</a><a href="#how" className="hover:text-white">How it works</a><a href="#motion" className="hover:text-white">Motion graphics</a><a href="#media" className="hover:text-white">Free media</a></nav><div className="hidden sm:flex items-center gap-2"><RouteLink href="/login" className="px-3 py-2 text-xs text-slate-400 hover:text-white">Login</RouteLink><RouteLink href="/signup" className="px-3 py-2 text-xs text-slate-300 hover:text-white">Sign up</RouteLink><RouteLink href="/app" className="rounded-full bg-white text-slate-950 hover:bg-violet-100 px-4 py-2.5 text-xs font-semibold">Try Rhymx</RouteLink></div><button onClick={() => setMenuOpen(!menuOpen)} className="sm:hidden p-2 text-slate-300" aria-label="Toggle navigation">{menuOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}</button></div>{menuOpen && <div className="sm:hidden border-t border-white/8 p-4 bg-[#0d0f14]"><div className="grid gap-2">{[['Features', '#features'], ['How it works', '#how'], ['Motion graphics', '#motion'], ['Free media', '#media']].map(([label, href]) => <a key={label} href={href} onClick={() => setMenuOpen(false)} className="rounded-lg px-3 py-2 text-sm text-slate-300 hover:bg-white/5">{label}</a>)}<RouteLink href="/login" className="rounded-lg px-3 py-2 text-sm text-slate-300">Login</RouteLink><RouteLink href="/signup" className="rounded-lg px-3 py-2 text-sm text-slate-300">Sign up</RouteLink><RouteLink href="/app" className="mt-2 rounded-lg bg-violet-600 px-3 py-3 text-sm text-center font-medium">Start editing free</RouteLink></div></div>}</header>

      <main>
        <section className="relative pt-36 sm:pt-44 pb-24 overflow-hidden"><div className="absolute inset-x-0 top-0 h-[740px] bg-[radial-gradient(circle_at_50%_5%,rgba(124,58,237,.28),transparent_48%)]" /><div className="landing-grid absolute inset-0 opacity-[.14]" /><div className="relative max-w-7xl mx-auto px-5 sm:px-8"><div className="max-w-4xl mx-auto text-center"><div className="inline-flex items-center gap-2 rounded-full border border-violet-400/20 bg-violet-500/10 px-3 py-1.5 text-[10px] uppercase tracking-[.17em] text-violet-200"><Sparkles className="h-3 w-3" />Browser-first AI video editing</div><h1 className="mt-7 text-[clamp(3.2rem,8vw,7.2rem)] leading-[.9] font-semibold tracking-[-.065em]">Turn narration into an <span className="text-transparent bg-clip-text bg-gradient-to-r from-violet-300 via-white to-cyan-300">editable video.</span></h1><p className="mt-7 max-w-2xl mx-auto text-base sm:text-lg leading-relaxed text-slate-400">Transcribe automatically. Match free stock and archival footage. Approve every scene. Add motion graphics. Edit and export—all in your browser.</p><div className="mt-9 flex flex-col sm:flex-row items-center justify-center gap-3"><button onClick={() => navigate('/app')} className="w-full sm:w-auto rounded-full bg-white text-slate-950 hover:bg-violet-100 px-6 py-3.5 text-sm font-semibold flex items-center justify-center gap-2">Start editing free<ArrowRight className="h-4 w-4" /></button><a href="#how" className="w-full sm:w-auto rounded-full border border-white/10 bg-white/5 hover:bg-white/10 px-6 py-3.5 text-sm flex items-center justify-center gap-2"><Play className="h-3.5 w-3.5" />See how it works</a></div><div className="mt-5 flex flex-wrap justify-center gap-x-5 gap-y-2 text-[10px] text-slate-600"><span className="flex items-center gap-1.5"><Check className="h-3 w-3 text-emerald-400" />No account required</span><span className="flex items-center gap-1.5"><Check className="h-3 w-3 text-emerald-400" />Local projects</span><span className="flex items-center gap-1.5"><Check className="h-3 w-3 text-emerald-400" />Editable timeline</span></div></div><div className="mt-16 sm:mt-20 max-w-5xl mx-auto relative"><div className="absolute -inset-10 bg-violet-600/10 blur-3xl rounded-full" /><div className="relative"><DemoTimeline /></div></div></div></section>

        <section id="features" className="py-24 border-y border-white/6 bg-[#0b0d12]"><div className="max-w-7xl mx-auto px-5 sm:px-8"><div className="max-w-2xl"><div className="section-kicker">A real editor, accelerated</div><h2 className="section-title">AI gets you to the timeline. You make the cut.</h2><p className="section-copy">Rhymx builds a strong first montage without flattening your creative decisions into a one-shot result.</p></div><div className="mt-12 grid sm:grid-cols-2 lg:grid-cols-4 gap-px rounded-3xl overflow-hidden border border-white/8 bg-white/8">{features.map(({ icon: Icon, title, copy }, index) => <article key={title} className={`bg-[#0d0f14] p-6 ${index === features.length - 1 ? 'sm:col-span-2 lg:col-span-1' : ''}`}><div className="h-10 w-10 rounded-xl border border-white/8 bg-white/5 text-violet-300 flex items-center justify-center"><Icon className="h-4.5 w-4.5" /></div><h3 className="mt-5 font-medium">{title}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{copy}</p></article>)}</div></div></section>

        <section id="how" className="py-28"><div className="max-w-7xl mx-auto px-5 sm:px-8"><div className="text-center max-w-2xl mx-auto"><div className="section-kicker">Four deliberate steps</div><h2 className="section-title">From voiceover to final cut.</h2></div><div className="mt-14 grid md:grid-cols-4 gap-4">{[['01', 'Import narration', 'Drop in your recorded voiceover. It stays the source audio for the finished video.'], ['02', 'Review generated scenes', 'Word timing and visual phrases turn the narration into a searchable scene plan.'], ['03', 'Approve footage and motion', 'Compare candidates, check licenses, replace weak matches, or choose a motion template.'], ['04', 'Edit and export', 'Refine timing, captions, tracks, and transforms, then render through WebCodecs.']].map(([number, title, copy]) => <article key={number} className="relative rounded-2xl border border-white/8 bg-white/[.025] p-6"><div className="text-5xl font-semibold tracking-[-.06em] text-white/10">{number}</div><h3 className="mt-5 font-medium">{title}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{copy}</p></article>)}</div></div></section>

        <section id="media" className="py-28 border-y border-white/6 bg-[#0b0d12]"><div className="max-w-7xl mx-auto px-5 sm:px-8 grid lg:grid-cols-[.85fr_1.15fr] gap-12 items-center"><div><div className="section-kicker">One search, accountable sources</div><h2 className="section-title">A broader visual vocabulary.</h2><p className="section-copy">Search modern stock, public collections, science imagery, and Commons media without losing the origin or usage context.</p><div className="mt-8 grid sm:grid-cols-2 gap-3">{[['Free API', 'Pexels · Pixabay'], ['Open / keyless', 'Archive.org · NASA · Wikimedia'], ['AI processing', 'Groq'], ['Composition', 'Remotion · HyperFrames']].map(([label, value]) => <div key={label} className="rounded-xl border border-white/8 bg-white/[.025] p-4"><div className="text-[9px] uppercase tracking-[.16em] text-slate-600">{label}</div><div className="mt-1 text-sm text-slate-300">{value}</div></div>)}</div><p className="mt-5 text-[10px] leading-4 text-slate-600">Providers can enforce quotas and usage rules. Rhymx never promises unlimited media or guaranteed commercial rights.</p></div><div className="rounded-3xl border border-white/8 bg-[#11131a] p-4 shadow-2xl"><div className="flex items-center gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-600" /><div className="h-10 rounded-xl bg-black/30 border border-white/8 pl-10 flex items-center text-xs text-slate-500">solar observatory orbit</div></div><div className="rounded-xl bg-violet-600 p-3"><Search className="h-4 w-4" /></div></div><div className="mt-3 flex flex-wrap gap-2">{['All free media', 'Video', 'Landscape', 'License: declared'].map((item, index) => <span key={item} className={`rounded-full border px-2.5 py-1 text-[9px] ${index === 0 ? 'border-violet-400/30 bg-violet-500/10 text-violet-200' : 'border-white/8 text-slate-500'}`}>{item}</span>)}</div><div className="mt-4 grid grid-cols-2 gap-3">{[['NASA', 'Public guidance', 'from-sky-700 to-indigo-950'], ['Wikimedia', 'CC BY-SA', 'from-emerald-700 to-slate-950'], ['Pexels', 'Pexels license', 'from-amber-600 to-rose-950'], ['Archive.org', 'Verify rights', 'from-fuchsia-700 to-slate-950']].map(([provider, license, color]) => <div key={provider} className="rounded-xl overflow-hidden border border-white/8 bg-black/20"><div className={`aspect-video bg-gradient-to-br ${color} landing-grid`} /><div className="p-2.5 flex items-center justify-between gap-2"><span className="text-[10px]">{provider}</span><span className="text-[8px] text-slate-600">{license}</span></div></div>)}</div></div></div></section>

        <section id="motion" className="py-28 overflow-hidden"><div className="max-w-7xl mx-auto px-5 sm:px-8"><div className="max-w-2xl"><div className="section-kicker">Two levels of motion</div><h2 className="section-title">Use motion where footage cannot say it better.</h2></div><div className="mt-12 grid lg:grid-cols-2 gap-5"><article className="rounded-3xl border border-white/8 p-7 sm:p-9 bg-[linear-gradient(145deg,rgba(124,58,237,.14),transparent_55%),#0d0f14]"><div className="h-11 w-11 rounded-xl bg-violet-500/15 text-violet-300 flex items-center justify-center"><Captions className="h-5 w-5" /></div><div className="mt-8 text-[10px] uppercase tracking-[.2em] text-violet-300">Integrated motion</div><h3 className="mt-2 text-3xl font-semibold tracking-tight">Built into the timeline.</h3><p className="mt-4 text-sm leading-6 text-slate-500">Captions, title cards, quotes, charts, calls to action, transitions, and repeatable templates preview and export from the same Remotion composition.</p><div className="mt-7 flex flex-wrap gap-2">{['Hero title', 'Statistic card', 'Quote', 'Progress bar', 'End card'].map((tag) => <span key={tag} className="rounded-full border border-white/8 px-3 py-1.5 text-[9px] text-slate-400">{tag}</span>)}</div></article><article className="rounded-3xl border border-fuchsia-400/15 p-7 sm:p-9 relative overflow-hidden bg-[radial-gradient(circle_at_80%_10%,rgba(236,72,153,.24),transparent_36%),linear-gradient(145deg,rgba(59,130,246,.13),transparent_55%),#0d0f14]"><div className="absolute -right-20 -top-24 h-64 w-64 rounded-[42%] border border-fuchsia-400/20 rotate-12" /><div className="h-11 w-11 rounded-xl bg-fuchsia-500/15 text-fuchsia-300 flex items-center justify-center"><MousePointer2 className="h-5 w-5" /></div><div className="mt-8 text-[10px] uppercase tracking-[.2em] text-fuchsia-300">Advanced motion</div><h3 className="mt-2 text-3xl font-semibold tracking-tight">Designed for the big moments.</h3><p className="mt-4 text-sm leading-6 text-slate-500">Template-driven kinetic typography, product launches, logo reveals, animated charts, lower thirds, and branded end cards keep editable variables for later rerenders.</p><div className="mt-7 flex flex-wrap gap-2">{['Kinetic title', 'Product launch', 'Logo reveal', 'Animated chart', 'Lower third'].map((tag) => <span key={tag} className="rounded-full border border-white/8 px-3 py-1.5 text-[9px] text-slate-400">{tag}</span>)}</div></article></div></div></section>

        <section className="py-28 border-y border-white/6 bg-[#0b0d12]"><div className="max-w-4xl mx-auto px-5 sm:px-8 text-center"><div className="h-14 w-14 rounded-2xl bg-violet-600 mx-auto flex items-center justify-center"><Database className="h-6 w-6" /></div><h2 className="section-title mt-7">Your project lives with you.</h2><p className="section-copy mx-auto">Projects persist in browser storage. Large acquired assets use the browser’s file storage when available, with a compatibility fallback. The final MP4 is rendered locally through WebCodecs.</p></div></section>

        <section className="py-28"><div className="max-w-4xl mx-auto px-5 sm:px-8"><div className="text-center"><div className="section-kicker">Questions, answered honestly</div><h2 className="section-title">Before you start.</h2></div><div className="mt-12 border-t border-white/8">{faqs.map(([question, answer]) => <details key={question} className="group border-b border-white/8"><summary className="cursor-pointer list-none py-5 flex items-center justify-between gap-4 text-sm font-medium"><span>{question}</span><ChevronDown className="h-4 w-4 text-slate-600 transition-transform group-open:rotate-180" /></summary><p className="pb-5 max-w-2xl text-xs leading-5 text-slate-500">{answer}</p></details>)}</div></div></section>

        <section className="px-5 sm:px-8 pb-24"><div className="max-w-7xl mx-auto rounded-[32px] border border-violet-400/15 bg-[radial-gradient(circle_at_50%_0%,rgba(124,58,237,.34),transparent_52%),#101119] py-20 px-6 text-center"><div className="section-kicker">Start with the voice you already recorded</div><h2 className="mt-4 text-4xl sm:text-6xl font-semibold tracking-[-.05em]">Make the first cut in minutes.</h2><p className="mt-5 text-sm text-slate-400">No account. No generated narrator. No one-shot black box.</p><RouteLink href="/app" className="mt-8 inline-flex items-center gap-2 rounded-full bg-white text-slate-950 hover:bg-violet-100 px-6 py-3.5 text-sm font-semibold">Start editing free<ArrowRight className="h-4 w-4" /></RouteLink></div></section>
      </main>

      <footer className="border-t border-white/8"><div className="max-w-7xl mx-auto px-5 sm:px-8 py-10 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-6"><div><Brand /><p className="mt-2 text-[10px] text-slate-600">Narration into editable video.</p></div><div className="flex flex-wrap gap-5 text-[10px] text-slate-500"><a href="#features" className="hover:text-white">Features</a><RouteLink href="/privacy" className="hover:text-white">Privacy</RouteLink><RouteLink href="/terms" className="hover:text-white">Terms</RouteLink><RouteLink href="/login" className="hover:text-white">Login</RouteLink></div></div></footer>
    </div>
  )
}
